#!/usr/bin/env bash

# Install nginx
apt-get update
apt-get -y install nginx

# Configure nginx to listen on port 80
sed -i 's/80 default_server/80/g' /etc/nginx/sites-available/default

# Restart nginx
echo "Restarting nginx..."
service nginx stop
service nginx start

# Check if nginx is running
if ! pgrep nginx > /dev/null
then
    echo "Nginx failed to start."
else
    echo "Nginx is up and running."
fi

# Check if nginx is serving the correct content
if curl -sI localhost | grep "Holberton School" > /dev/null
then
    echo "Nginx is serving the correct content."
else
    echo "Nginx is not serving the correct content."
fi
