#!/usr/bin/env bash
# Install Nginx on Ubuntu
sudo apt update
sudo apt install nginx -y
# Allow Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'
# Create a custom HTML file with the string Holberton School
echo "<html><head><title>Nginx Test</title></head><body><h1>Holberton School for the win!</h1></body></html>" | sudo tee /var/www/html/index.nginx-debian.html
# Restart Nginx using service command
sudo service nginx restart

